### ISSUE TITLE
Add functionality to deploy to pypi and testpypi.python.org in .travis.yml

### ISSUE THREAD

**Issue by fhightower** [fhightower/python-project-template#10]
See the example below (from https://github.com/fhightower/onemillion):

```
# This file was autogenerated and will overwrite each time you run travis_pypi_setup.py
deploy:
    # production pypi
  - provider: pypi
    distributions: sdist
    user: cartiergoldfinch
    password:
      secure: lZGfyeZhV9wTF142yDL1TTg74VeBPAdDtfXQkMriwzGdGSQniRRzw682ublV8ElzKkssji9yIv4U0mtN+GaF1dZAd4oQ00Q9h27SWPR0rBpaAy/2JKqUn5ojlW+xEtD5UNPKHxBGK1ZQ4xmE/WKbTph1kJRjvWSx8MeKudlFr9ix9SoEz1DFCPAX7NX111IhqWs7uZC7Iu9YHWMKYlPDEyQRQ8493Q45A0PcRQ9Eab92Qw/Mh8RNHuU2pYNlpCceG0yI/ZAeExLnTxR/Bscb+XjOwF56KXGyFfZYcaObIFOfMrgt3neoHY07Hrxp5rhpE5lH8QSWF3u3eY+CWYh5wH5ghSzv3YRQYUVZF69qQkJjbF6F/MV5WwtqavtY5sLuWNRnIS779VinvdHkn8fYNwseDxnwi+Fzcg8/9Zl7Gd9GkMSYsDj9tiar1HhunpL6bwohixgPE2z6J8/zAchmd1sPT1r32b1cDw7ellfxTa7e6OjtTTifVgLVdu8aNwwifjrGxVLQ1qUk4bSNYw8OMqKs2Eo0CpHzJOHljKyYQqlrS/ZmVOWo3GLMtqDoWCgITognQyrfpQhVwn6QpVbEVOltGqc8xDOyreqaWkwc1NNMfjS7UAE4b/FCS6YyYhEgTWYHeqW5Hl2Cj3/ptbMh3K8hgWkY8KJIMs7HcSODPuw=
    on:
      branch: master
      repo: fhightower/onemillion
      tags: true
      condition: $TOXENV == py27
    # test pypil
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: tagsarmenian
    password:
      secure: gSTrY5nOrrGbHhyPCiXlg3T1LicnL1FXw/oDloUIRb1by51lVivMUCoiGXjRdQTaFN8ka/79X7jAWlbmUNK0m6AK6NwOWDB+i98Y1ieKsYb5AsY14bCUOaKo0B8TiJtKK9Cclw7D2qi/zFw/Wq9kpVhWSnyABx7juNxwggEqqWnshXGxQwBgGW3trbK3ae+Kotr9joDOn09kdAv1nS+XmJ7kSzNaNy7lsCSqqoqkxyuefIpsYIWOD5rWIgXGnRfFDcolZU4Dezff57h/r2x/sSmiWltjsALumXHF3+l8bK/BzHtxosqGg0Di4tMGOef11zgmyxKa8wIG0e7alerHrzBMSWEjmtxdG/HYgDAlmDz+rwkW2iX0zOdHv4ELPUspy7+sCcKc7xikrZzriWrsP2Yx9Kuk9Jj8s119O3Wisx9036UC07zlFMgAIkonLkb2YJykdgbaCySZ9YD+ybGfv4F42dMu5gWdjujOWCVyJIAd1yY5Rtdr8masRPuENWxL7qPhTldd2qvN8IXtP2hDgdvGe4gNXsBBQYHcBBANgWAJArJhr8zlpZL0rLo3z/AQlmfxwL4H1R+ho+btvba6nawzKFJ/YEEK+dZPbTVJyMIrr+q3qjA0Bih/Eb/lw3V3hxYo+gqErzp/hpbpjN7dIs14U1Oc3/uNHco7u7JPLYA=
    on:
      branch:
        - dev
        - master
      tags: false
      repo: fhightower/onemillion
      condition: $TOXENV == py27
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
install: pip install -U tox
language: python
python: 3.5
script: tox -e ${TOXENV}
```
